[package]
name = "egs-api"
version = "0.1.2"
authors = ["Milan Šťastný <milan@acheta.games>"]
description  = "Interface to the Epic Games API"
categories = ["asynchronous"]
keywords = ["EpicGames", "Epic", "egs"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/AchetaGames/egs-api-rs"
documentation = "https://docs.rs/egs-api/latest/egs_api/"

edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webbrowser = "0.5.5"
reqwest = { version = "0.11", features = ["json", "cookies"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[dependencies.tokio]
version = "1.2.0"
features = ["full"]

[dependencies.serde]
version = "1.0.123"
features = ["derive"]