[package]
name = "egs-api"
version = "0.1.0"
authors = ["mistastn <mistastn@cisco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webbrowser = "0.5.5"
reqwest = { version = "0.11", features = ["json", "cookies"] }
serde_json = "1.0"

[dependencies.tokio]
version = "1.2.0"
features = ["full"]

[dependencies.serde]
version = "1.0.123"
features = ["derive"]