[package]
name = "egs-api"
version = "0.1.0"
authors = ["mistastn <mistastn@cisco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webbrowser = "0.5.5"
hyper-tls = "0.5"

[dependencies.hyper]
version = "0.14"
features = ["client", "http1", "http2"]

[dependencies.tokio]
version = "1.2.0"
features = ["full"]