[package]
name = "egs-api"
version = "0.1.3"
authors = ["Milan Šťastný <milan@acheta.games>"]
description = "Interface to the Epic Games API"
categories = ["asynchronous"]
keywords = ["EpicGames", "Epic", "egs"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/AchetaGames/egs-api-rs"
documentation = "https://docs.rs/egs-api/latest/egs_api/"

edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webbrowser = "0.5.5"
reqwest = { version = "0.11", features = ["json", "cookies", "blocking"] }
serde_json = "1.0"
url = { version = "2.2.1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"

[dependencies.tokio]
version = "1.2.0"
features = ["full"]

[dependencies.serde]
version = "1.0.123"
features = ["derive"]

[dev-dependencies]
gtk = "^0.9.0"
gdk-pixbuf = "0.9.0"
glib = "0.10.3"
pango = "0.9.1"
relm = "^0.21.0"
relm-derive = "^0.21.0"
threadpool = "1.8.1"