name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --lib
    - name: Run tests
      run: cargo test --tests --lib
